version: '3'
services:
  app:
    build: .
    container_name: 'helpanto'
    command: npm start
    environment:
      - PORT=3003
      - RECIPE_SERVER_URL=${RECIPE_SERVER_URL}
    volumes:
      - .:/usr/src/
      - /usr/src/node_modules
    ports:
      - 3003:3003
