/* error-actions.js */
export const ENQUEUE_ERROR = 'ENQUEUE_ERROR';
export const DEQUEUE_ERROR = 'DEQUEUE_ERROR';

/* modal-actions.js */
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

/* recipe-actions.js */
export const SELECT_RECIPE_ON_LIST = 'SELECT_RECIPE_ON_LIST';
export const DESELECT_RECIPE_ON_LIST = 'DESELECT_RECIPE_ON_LIST';
export const FILTER_RECIPE_LIST = 'FILTER_RECIPE_LIST';
export const REQUEST_GET_RECIPES = 'REQUEST_GET_RECIPES';
export const REQUEST_GET_RECIPES_SUCCESS = 'REQUEST_GET_RECIPES_SUCCESS';
export const REQUEST_GET_RECIPES_FAILURE = 'REQUEST_GET_RECIPES_FAILURE';
export const REQUEST_POST_RECIPE = 'REQUEST_POST_RECIPE';
export const REQUEST_POST_RECIPE_SUCCESS = 'REQUEST_POST_RECIPE_SUCCESS';
export const REQUEST_POST_RECIPE_FAILURE = 'REQUEST_POST_RECIPE_FAILURE';
export const REQUEST_DELETE_RECIPE = 'REQUEST_DELETE_RECIPE';
export const REQUEST_DELETE_RECIPE_SUCCESS = 'REQUEST_DELETE_RECIPE_SUCCESS';
export const REQUEST_DELETE_RECIPE_FAILURE = 'REQUEST_DELETE_RECIPE_FAILURE';
